name: Test examples
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  llama3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/01_llama3/scripts/llama3.sh

  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/02_eval/scripts/eval.sh

  prompt_tuning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/03_prompt_tuning/scripts/prompt_tune.sh

  rag_tuning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/04_rag_tuning/scripts/rag_tuning.sh

  data_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/05_data_pipeline/scripts/generate-data.sh

  ift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/06_ift/scripts/train.sh

  json_output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          mkdir ~/.lamini/
          echo 'production:' >> ~/.lamini/configure.yaml
          echo '  key: ${{ secrets.API_TOKEN }}' >> ~/.lamini/configure.yaml
      - run: ./lamini-examples/10_json_output/scripts/run_llm_json.sh
